### PR TITLE
adjust notification position

### PR DESCRIPTION
**Pull request by gcziprusz**
Changes:
- Added console to jshint globals. You can now use console.log without having to specify /*globals console*/
- Removed css prefixes
- changed nav styling + simplified tooltip
- move notification bubble :point_down: 

screen shot 2015-04-10 at 12 10 06 pm
screen shot 2015-04-10 at 12 10 00 pm

### CODE REVIEW

**Comment by gcziprusz** [comment]
https://github.com/lonelyplanet/destinations-next/pull/64

**Comment by stevebrownlee** [comment]
Please provide some steps on how your teammates can test, and validate, this PR.  Thanks.

**Comment by gcziprusz** [comment]
- goto shop.lonelyplanet.com add stuff to your cart
- add hosts file entry 127.0.0.1 lonelyplanet.com so shop cookie can be read
- visit page lonelyplanet.com:3000/asia
- verify that notification bubble is positioned correctly. 

- add console.log to any js file and make sure grunt is :green_heart: 
- load mobile page in safari and make sure nav animation is smooth (verifies that prefixes are added)

**Comment by davidthesavage** [comment]
:+1:

**Pull request merged**
